-- Kartoteka opreme: časovnica zapisov o tem, kaj se je dogajalo z opremo

create table if not exists public.rbo_kartoteka (
    id             bigint generated by default as identity primary key,
    id_oprema      bigint not null references public.rbo_oprema (id) on delete cascade,
    datum_vnosa    date not null default current_date,
    besedilo_vnosa text not null check (length(trim(besedilo_vnosa)) > 0)
);

create index if not exists rbo_kartoteka_oprema_idx on public.rbo_kartoteka (id_oprema, datum_vnosa desc);

alter table public.rbo_kartoteka enable row level security;

drop policy if exists "fines beri" on public.rbo_kartoteka;
drop policy if exists "fines dodaj" on public.rbo_kartoteka;
drop policy if exists "fines uredi" on public.rbo_kartoteka;
create policy "fines beri" on public.rbo_kartoteka for select to authenticated using (public.rbo_je_fines_uporabnik());
create policy "fines dodaj" on public.rbo_kartoteka for insert to authenticated with check (public.rbo_je_fines_uporabnik());
create policy "fines uredi" on public.rbo_kartoteka for update to authenticated
    using (public.rbo_je_fines_uporabnik()) with check (public.rbo_je_fines_uporabnik());
