-- Slike opreme (Excel: list TabelaSlike + stolpec "Predstavna slika" na listu POPIS)
-- Na opremo: 1 predstavna + do 6 dodatnih slik.
-- Ime datoteke v Supabase Storage: "{id_oprema} - predstavna.jpg" oz. "{id_oprema} - Slika{n}.jpg"

create table if not exists public.rbo_slike (
    id          bigint generated by default as identity primary key,
    id_oprema   bigint not null references public.rbo_oprema (id) on delete cascade,
    vrsta_slike text not null check (vrsta_slike in (
                    'Predstavna', 'Slika1', 'Slika2', 'Slika3', 'Slika4', 'Slika5', 'Slika6')),
    ime_slike   text not null,
    unique (id_oprema, vrsta_slike)   -- vsaka vrsta največ enkrat na opremo => največ 7 slik
);

alter table public.rbo_slike enable row level security;

-- Pogled za prikaz: vsa oprema s predstavno sliko in (morebitnimi) prodajnimi podatki.
-- Oprema brez prodaje se prikaže s praznimi prodajnimi stolpci.
drop view if exists public.v_oprema_prodaja;  -- staro ime pogleda

create or replace view public.v_rbo_oprema_prodaja
with (security_invoker = true) as
select
    o.id                      as id_oprema,
    o.datum_prejema,
    ps.ime_slike              as predstavna_slika,
    o.kolicina,
    o.em,
    o.koda,
    o.serijska_stevilka,
    o.leto_proizvodnje,
    o.skupina_opreme,
    o.oprema_naziv,
    o.lastnistvo,
    o.skladisce,
    o.komentar,
    o.ocena,
    p.id_prodaja,
    p.imenovani_prodajalec,
    p.garancijski_rok_meseci,
    p.cena_nove,
    p.rabat_procent,
    p.prodajna_cena,
    p.datum_prodaje,
    p.komentar_ob_prodaji,
    p.status_prodaje
from public.rbo_oprema o
left join public.rbo_slike ps on ps.id_oprema = o.id and ps.vrsta_slike = 'Predstavna'
left join public.ln_rbo_oprema_prodaja po on po.id_oprema = o.id
left join public.rbo_prodaja p on p.id_prodaja = po.id_prodaja;
