-- Prodajne aktivnosti (Excel: list POPIS, stolpci O–V) in povezava z rabljeno opremo

-- 1) Prodaja
create table if not exists public.rbo_prodaja (
    id_prodaja             bigint generated by default as identity primary key,
    imenovani_prodajalec   text,                                               -- O: Imenovani_prodajalec
    garancijski_rok_meseci smallint check (garancijski_rok_meseci >= 0),      -- P: Garancijski_rok (brez = 0, 1 leto = 12)
    cena_nove              numeric(12,2) check (cena_nove >= 0),               -- Q: Cena_nove (EUR)
    rabat_procent          numeric(5,2) check (rabat_procent between 0 and 100), -- R: Rabat (%)
    prodajna_cena          numeric(12,2) check (prodajna_cena >= 0),           -- S: Prodajna_cena (EUR)
    datum_prodaje          date,                                               -- T: Datum_prodaje
    komentar_ob_prodaji    text,                                               -- U: Komentar_ob_prodaji
    status_prodaje         text check (status_prodaje in (                     -- V: Status_prodaje (šifrant)
                               '0. NI ZA PRODAJO',
                               '1. NI UREJENO ZA PRODAJO',
                               '2. NEPRODANO',
                               '3. PRODANO',
                               '4. POSOJENO'))
);

create index if not exists rbo_prodaja_status_idx on public.rbo_prodaja (status_prodaje);

-- 2) Povezovalna tabela: katera oprema je v kateri prodaji
--    (ena prodaja ima lahko več kosov opreme, en kos lahko več aktivnosti, npr. posojeno -> prodano)
create table if not exists public.ln_rbo_oprema_prodaja (
    id_prodaja bigint not null references public.rbo_prodaja (id_prodaja) on delete cascade,
    id_oprema  bigint not null references public.rbo_oprema (id) on delete cascade,
    primary key (id_prodaja, id_oprema)
);

create index if not exists ln_rbo_oprema_prodaja_oprema_idx on public.ln_rbo_oprema_prodaja (id_oprema);

alter table public.rbo_prodaja enable row level security;
alter table public.ln_rbo_oprema_prodaja enable row level security;
