-- Tabela rabljene opreme (Excel: ZALOGA - RABLJENA_OPREMA, list POPIS, stolpci A–N)
-- Stolpec C (Predstavna slika) je v tabeli rbo_slike (vrsta_slike = 'Predstavna').

create table if not exists public.rbo_oprema (
    id                 bigint generated by default as identity primary key, -- A: ID
    datum_prejema      date,                                                -- B: Datum_prejema
    kolicina           integer not null default 1 check (kolicina >= 0),    -- D: Kol
    em                 text default 'kos',                                  -- E: EM (kos, kpl)
    koda               text,                                                -- F: Koda
    serijska_stevilka  text,                                                -- G: Serijska_stevilka
    leto_proizvodnje   smallint check (leto_proizvodnje between 1950 and 2100), -- H: Leto_proizvodnje
    skupina_opreme     text,                                                -- I: Skupina_opreme
    oprema_naziv       text not null,                                       -- J: Oprema_naziv
    lastnistvo         text,                                                -- K: Lastnistvo
    skladisce          text,                                                -- L: Skladisce
    komentar           text,                                                -- M: Komentar
    ocena              smallint check (ocena between 1 and 6)               -- N: Ocena peči
);

create index if not exists rbo_oprema_skupina_idx on public.rbo_oprema (skupina_opreme);
create index if not exists rbo_oprema_serijska_idx on public.rbo_oprema (serijska_stevilka);

-- RLS vklopljen; politike dodamo, ko povežemo Vercel app in avtentikacijo.
alter table public.rbo_oprema enable row level security;
