-- AI iskanje (poskusno): »Iščeš rabljeno opremo? Napiši, kaj iščeš.« na domači strani.
-- Vektorje (384 števil) izračuna brskalnik z odprtokodnim modelom multilingual-e5-small (Transformers.js),
-- baza jih samo hrani in vrne najbolj podobno opremo. Obstoječe tabele in pogledi se ne spreminjajo.
-- ODSTRANITEV: poženi supabase/ai_iskanje_odstrani.sql (glej tudi src/components/ai-iskanje/README.md).

-- 1) Razširitev pgvector (v Supabase je že na voljo, samo vklopi se)
create extension if not exists vector with schema extensions;

-- 2) Vektor za vsak kos opreme; besedilo = iz česa je bil vektor izračunan (ob spremembi se izračuna znova)
create table if not exists public.rbo_ai_vektor (
    id            bigint generated by default as identity primary key,
    id_oprema     bigint not null unique references public.rbo_oprema (id) on delete cascade,
    besedilo      text not null,
    vektor        extensions.vector(384) not null,
    posodobljeno  timestamptz not null default now()
);

-- 3) RLS: izpeljani podatki, zato jih lahko zapiše vsak uporabnik @fines.si (tudi "samo ogled"),
--    da se vektorji pripravijo ob prvem iskanju kogarkoli
alter table public.rbo_ai_vektor enable row level security;

drop policy if exists "fines beri" on public.rbo_ai_vektor;
drop policy if exists "fines dodaj" on public.rbo_ai_vektor;
drop policy if exists "fines uredi" on public.rbo_ai_vektor;
create policy "fines beri" on public.rbo_ai_vektor for select to authenticated
    using (public.rbo_je_fines_uporabnik());
create policy "fines dodaj" on public.rbo_ai_vektor for insert to authenticated
    with check (public.rbo_je_fines_uporabnik());
create policy "fines uredi" on public.rbo_ai_vektor for update to authenticated
    using (public.rbo_je_fines_uporabnik()) with check (public.rbo_je_fines_uporabnik());

-- 4) Iskanje: najbolj podobna oprema glede na vektor vprašanja (kosinusna podobnost, 1 = enako)
create or replace function public.rbo_ai_isci(poizvedba extensions.vector(384), stevilo integer default 30)
returns table (id_oprema bigint, podobnost double precision)
language sql
stable
security invoker
set search_path = public, extensions
as $$
    select v.id_oprema, 1 - (v.vektor <=> poizvedba) as podobnost
    from public.rbo_ai_vektor v
    order by v.vektor <=> poizvedba
    limit stevilo
$$;

grant execute on function public.rbo_ai_isci(extensions.vector, integer) to authenticated;
