-- 1) Kartoteka: strošek zapisa v EUR (neobvezno)
alter table public.rbo_kartoteka
    add column if not exists strosek numeric(12,2) check (strosek >= 0);

-- 2) Tehnični list (en na opremo; polja kot v Power Apps tabeli tehnicni_listi)
create table if not exists public.rbo_tehnicni_list (
    id                  bigint generated by default as identity primary key,
    id_oprema           bigint not null unique references public.rbo_oprema (id) on delete cascade,
    -- Osnovni podatki
    tip_opreme          text,
    naziv               text,
    leto_izdelave       smallint check (leto_izdelave between 1950 and 2100),
    serijska            text,
    dimenzija           text,
    teza                text,
    -- Podatki obratovanja
    delovne_ure         text,
    prikljucna_moc      text,
    elektricni_priklop  text,
    varovalke           text,
    temperatura         text,
    priklop_vode        text,
    odvod_pare          text,
    -- Peka
    kapaciteta_pekacev  text,
    razdalja_med_pekaci text,
    -- Opis
    opis                text
);

alter table public.rbo_tehnicni_list enable row level security;
drop policy if exists "fines beri" on public.rbo_tehnicni_list;
drop policy if exists "fines dodaj" on public.rbo_tehnicni_list;
drop policy if exists "fines uredi" on public.rbo_tehnicni_list;
create policy "fines beri" on public.rbo_tehnicni_list for select to authenticated using (public.rbo_je_fines_uporabnik());
create policy "fines dodaj" on public.rbo_tehnicni_list for insert to authenticated with check (public.rbo_je_fines_uporabnik());
create policy "fines uredi" on public.rbo_tehnicni_list for update to authenticated
    using (public.rbo_je_fines_uporabnik()) with check (public.rbo_je_fines_uporabnik());

-- 3) Slika krmiljenja ("{id} - krmiljenje.jpg") je v rbo_slike z vrsto 'Krmiljenje'
alter table public.rbo_slike drop constraint if exists rbo_slike_vrsta_slike_check;
alter table public.rbo_slike drop constraint if exists slike_vrsta_slike_check;
alter table public.rbo_slike add constraint rbo_slike_vrsta_slike_check check (vrsta_slike in (
    'Predstavna', 'Slika1', 'Slika2', 'Slika3', 'Slika4', 'Slika5', 'Slika6', 'Krmiljenje'));

-- 4) Pogled: dodan stolpec ima_tehnicni_list (na koncu, da create or replace deluje)
create or replace view public.v_rbo_oprema_prodaja
with (security_invoker = true) as
select
    o.id                      as id_oprema,
    o.datum_prejema,
    ps.ime_slike              as predstavna_slika,
    o.kolicina,
    o.em,
    o.koda,
    o.serijska_stevilka,
    o.leto_proizvodnje,
    o.skupina_opreme,
    o.oprema_naziv,
    o.lastnistvo,
    o.skladisce,
    o.komentar,
    o.ocena,
    p.id_prodaja,
    p.imenovani_prodajalec,
    p.garancijski_rok_meseci,
    p.cena_nove,
    p.rabat_procent,
    p.prodajna_cena,
    p.datum_prodaje,
    p.komentar_ob_prodaji,
    p.status_prodaje,
    exists (select 1 from public.rbo_tehnicni_list tl where tl.id_oprema = o.id) as ima_tehnicni_list
from public.rbo_oprema o
left join public.rbo_slike ps on ps.id_oprema = o.id and ps.vrsta_slike = 'Predstavna'
left join lateral (
    select pr.*
    from public.ln_rbo_oprema_prodaja po
    join public.rbo_prodaja pr on pr.id_prodaja = po.id_prodaja
    where po.id_oprema = o.id and pr.visible
    order by pr.id_prodaja desc
    limit 1
) p on true
where o.visible;
